# Generated by Django 5.0.1 on 2026-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
