# Generated by Django 5.0.1 on 2026-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
