# Generated by Django 5.0.1 on 2026-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_courseenrollment_phone_alter_studentprofile_phone'),
        ('subjects', '0003_subject_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs Registratsiyasi', 'verbose_name_plural': 'Kurs Registratsiyalari'},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_enrollment'),
        ),
    ]
