# Generated by Django 5.0.1 on 2026-06-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_courseenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='teacher',
        ),
    ]
