# Generated by Django 5.0.1 on 2026-05-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('students', '0002_classgroup_studentprofile_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='students.classgroup'),
        ),
    ]
