# Generated by Django 5.0.1 on 2026-05-24 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_class_group'),
        ('students', '0005_alter_courseenrollment_options_and_more'),
        ('subjects', '0003_subject_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('class_name', 'day', 'start_time'), name='unique_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='start_before_end_time'),
        ),
    ]
